apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golist
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: redis
        path: apps/redis
      - srv: mongodb
        path: apps2/mongo
      - srv: nginx
        path: apps2/nginx
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: golist-component
              operator: In
              values:
                - redis
        - matchExpressions:
            - key: golist-component
              operator: In
              values:
                - mongodb
        - matchExpressions:
            - key: golist-component
              operator: In
              values:
                - nginx