apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/dependency: redis-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: mongodb
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 13.6.0
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true