apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/dependency: operator-redis
    argocd.argoproj.io/dependency.wait: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/dependency: operator-redis
    argocd.argoproj.io/dependency.wait: "true"
spec:
  project: default
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: redis